blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<int:pk>/', views.PostDetail.as_view()),
    # path('<int:pk>', views.single_post_page),
    # path('', views.index),
    path('', views.PostList.as_view()),
]

cobi_prj/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('qna/', include('qna.urls')),
    path('', include('single_pages.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

qna/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.PostList.as_view()),
    path('<int:pk>/', views.PostDetail.as_view()),
    path('category/<str:slug>/', views.category_page),
    path('create_post/', views.PostCreate.as_view()),
    path('update_post/<int:pk>/', views.PostUpdate.as_view()),

]

single_pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('self/', views.self),
    path('qqq/', views.qqq),
    path('searchhospital/', views.searchhospital),
    path('search_hospital_seoul/', views.search_hospital_seoul),
    path('search_hospital_incheon/', views.search_hospital_incheon),
    path('search_hospital_busan/', views.search_hospital_busan),
    path('post_one_list/', views.post_one_list),
    path('post_one_list2/', views.post_one_list2),
    path('', views.landing),
]

QnA/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=100)
    context = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'[{self.pk}]{self.title}'

blog/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()

    head_image = models.ImageField(upload_to='blog/image/%Y/%m/%d/', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'[{self.pk}]{self.title}'

    def get_absolute_url(self):
        return f'/blog/{self.pk}/'

qna/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/qna/category/{self.slug}/'

    class Meta:
        verbose_name_plural = 'Categories'


class Post(models.Model):
    title = models.CharField(max_length=100)
    context = models.TextField()

    head_image = models.ImageField(upload_to='qna/images/%Y/%m/%d/', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    author = models.ForeignKey(User, on_delete=models.CASCADE)

    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f'[{self.pk}]{self.title} :: {self.author} :: {self.category}'

    def get_absolute_url(self):
        return f'/qna/{self.pk}/'

single_pages/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Post

# Create your views here.

class PostList(ListView):
    model = Post
#    template_name = 'blog/medi.html'
    ordering = '-pk'

class PostDetail(DetailView):
     model = Post

# def index(request):
#     posts = Post.objects.all().order_by('-pk')
#
#     return render(
#         request,
#         'blog/post_list-real.html',
#         {
#             'posts': posts,
#         }
#     )
#
# def single_post_page(request, pk):
#     post = Post.objects.get(pk=pk)
#
#     return render(
#         request,
#         'blog/post_detail.html',
#         {
#             'post': post,
#         }
#     )

qna/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import Post, Category
from django.core.exceptions import PermissionDenied

# Create your views here.

class PostList(ListView):
    model = Post
    ordering = '-pk'

    def get_context_data(self, **kwargs):
        context = super(PostList, self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count()
        return context

class PostDetail(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count()
        return context

class PostCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Post
    fields = ['title', 'context', 'head_image', 'category']

    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated and (current_user.is_staff or current_user.is_superuser):
            form.instance.author = current_user
            return super(PostCreate, self).form_valid(form)
        else:
            return redirect('/qna/')

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff

class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title', 'context', 'head_image', 'category']

    template_name = 'qna/post_update_form.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(PostUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied


def category_page(request, slug):
    if slug == 'no_category':
        category = '기타 의료 질문'
        post_list = Post.objects.filter(category=None)
    else:
        category = Category.objects.get(slug=slug)
        post_list = Post.objects.filter(category=category)


    return render(
        request,
        'qna/post_list.html',
        {
            'post_list': post_list,
            'categories': Category.objects.all(),
            'no_category_post_count': Post.objects.filter(category=None).count(),
            'category': category,
        }
    )


# def index(request):
#     return render(
#         request,
#         'qna/post_list.html',
#     )
#
# def single_post_page(request, pk):
#     return render(
#         request,
#         'qna/post_detail.html',
#     )

single_pages/views.py
from django.shortcuts import render

# Create your views here.
def landing(request):
    return render(
        request,
        'single_pages/medi.html'
    )

def qqq(request):
    return render(
        request,
        'single_pages/qqq.html'
    )

def searchhospital(request):
    return render(
        request,
        'single_pages/searchhospital.html'
    )

def search_hospital_seoul(request):
    return render(
        request,
        'single_pages/search_hospital_seoul.html'
    )

def search_hospital_incheon(request):
    return render(
        request,
        'single_pages/search_hospital_incheon.html'
    )

def search_hospital_busan(request):
    return render(
        request,
        'single_pages/search_hospital_busan.html'
    )

def self(request):
    return render(
        request,
        'single_pages/self.html'
    )

def post_one_list(request):
    return render(
        request,
        'single_pages/post_one_list.html'
    )

def post_one_list2(request):
    return render(
        request,
        'single_pages/post_one_list2.html'
    )

blog/templates/blog/footer.html
<!doctype html>
{% load static %}
<html lang="ko">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.82.0">
    <title>COBI Medical Journal</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/blog/">



    <!-- Bootstrap core CSS -->
<link href="{% static 'blog/bootstrap/bootstrap.min.css' %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
      .mainbox{
        display: flex;
        justify-content: space-evenly;
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="blog.css" rel="stylesheet">
  </head>

<footer class="blog-footer">
  <p>COBI Medical Journal Technical Assistance <a href="https://twitter.com/mdo">mdo</a>.</p>
    <a href="#">맨 위로 가기</a>
  </p>
</footer>

blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>blog</title>
</head>
<body>

 <h1>cobi</h1>

{% for p in posts %}
   <hr/>
   <h2>{{ p.title }}</h2>
   <h4>{{ p.created_at }}</h4>
   <p>{{ p.content }}</p>
{% endfor %}

</body>
</html>

blog/templates/blog/navbar.html
<!doctype html>
{% load static %}
<html lang="ko">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.82.0">
    <title>COBI Medical Journal</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/blog/">



    <!-- Bootstrap core CSS -->
<link href="{% static 'blog/bootstrap/bootstrap.min.css' %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      a{
    text-decoration: none;
    text-decoration-color: black;
    text-decoration-line: none;
  }
  a:link { color: black; text-decoration: none;}
 a:visited { color: black; text-decoration: none;}
 a:hover { color: black; text-decoration: underline;}

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
      .mainbox{
        display: flex;
        justify-content: space-evenly;
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'blog/bootstrap/blog.css' %}" rel="stylesheet">
  </head>
  <body>

<div class="container">
  <header class="blog-header py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
      <div class="col-4 pt-1">
        <a class="link-secondary" href="#">맞춤형 정보 구독 안내</a>
      </div>
      <div class="col-4 text-center">
        <a class="blog-header-logo text-dark" href="/">COBI Medical</a>
      </div>
      <div class="col-4 d-flex justify-content-end align-items-center">
        <a class="link-secondary" href="#" aria-label="Search">
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img" viewBox="0 0 24 24"><title>Search</title><circle cx="10.5" cy="10.5" r="7.5"/><path d="M21 21l-5.2-5.2"/></svg>
        </a>
        <a class="btn btn-sm btn-outline-secondary" href="#">회원가입 | 로그인</a>
      </div>
    </div>
  </header>

  <div class="nav-scroller py-1 mb-2">
    <nav class="nav d-flex justify-content-between">
      <a class="p-2 link-secondary" href="/">전체</a>
      <a class="p-2 link-secondary" href="/blog/">의학뉴스</a>
      <a class="p-2 link-secondary" href="/searchhospital/">병원찾기</a>
      <a class="p-2 link-secondary" href="/qna/">Q&A</a>
      <a class="p-2 link-secondary" href="/self/">건강자가진단</a>
    </nav>
  </div>
</div>

blog/templates/blog/post_detail.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>{{ post.title }} - Blog</title>


<style>
.container{ margin: 30px;}
</style>
</head>
<body>

<nav>
    {% include 'blog/navbar.html' %}
</nav>

<div class="news">
    <div class="container">
<h1>{{ post.title }}</h1>
    <img class="card-img-top" style="width: 300px; margin: 0px 10px 0px 410px" src="{{ post.head_image.url }}"   alt="...">
<h4>{{ post.created_at }}</h4>
<p>{{ post.content }}</p>
<hr/>

 <div id="comment-area">
        <div class="container">
            <div class="co-3">
                <!-- Comments Form -->
                <div class="card my-4">
                  <h5 class="card-header">Leave a Comment:</h5>
                  <div class="card-body">
                    <form>
                      <div class="form-group">
                        <textarea class="form-control" rows="3"></textarea>
                      </div>
                      <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                  </div>
                </div>

                <!-- Single Comment -->
                <div class="media mb-4">
                  <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
                  <div class="media-body">
                    <h5 class="mt-0">Commenter Name</h5>
                    Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                  </div>
                </div>

                <!-- Comment with nested comments -->
                <div class="media mb-4">
                  <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
                  <div class="media-body">
                    <h5 class="mt-0">Commenter Name</h5>
                    Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                  </div>
                </div>

                    <div class="media mt-4">
                      <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
                      <div class="media-body">
                        <h5 class="mt-0">Commenter Name</h5>
                        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                      </div>
                    </div>

                    <div class="media mt-4">
                      <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
                      <div class="media-body">
                        <h5 class="mt-0">Commenter Name</h5>
                        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                      </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
</body>
</html>
</div>

{% include 'blog/footer.html' %}

blog/templates/blog/post_list.html
<!doctype html>
{% load static %}
<html lang="ko">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.82.0">

    <title>COBI Medical Journal</title>

    <link rel="stylesheet" href="{% static 'blog/bootstrap/bootstrap.min.css' %}" media="screen">

    <!-- Bootstrap core CSS -->
<link href="{% static 'blog/bootstrap/bootstrap.min.css' %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .mainbox{
        display: flex;
        justify-content: space-evenly;
      }
      .down{
      margin-bottom: 5px
      }

      .container{ margin: 30px;}

    </style>


    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'blog/bootstrap/blog.css' %}" rel="stylesheet">
  </head>
  <body>

 {% include 'blog/navbar.html' %}

<main class="container">
  <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
    <div class="col-md-6 px-0">
      <h1 class="display-4 fst-italic">의학 뉴스</h1>

    </div>
  </div>

  {% for p in post_list %}
   <div class="bottom">
  <div class="card mb-3" style="width: 1000px; height: 200px; margin-left: 50px;">
    <div class="row g-0">
      <div class="col-md-3">
        <img class="card-img-top" style="width: 200px; height: 200px; margin: 0px 10px 0px 40px" src="{{ p.head_image.url }}"   alt="...">
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title"><b>{{ p.title }}</b></h5>
          <p class="card-text">{{ p.content | truncatewords:10 }}</p>
          <p class="card-text"><small class="text-muted">{{ p.created_at }}</small></p>
          <a class="btn btn-primary" href="{{ p.get_absolute_url }}" role="button">자세히 보기</a>
        </div>
      </div>
    </div>
  </div>
   </div>
  {% endfor %}
</main><!-- /.container -->

{% include 'blog/footer.html' %}



  </body>
</html>

blog/templates/blog/single_post_page.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>{{ post.title }} - Blog</title>
</head>
<body>

<nav>
    <a href="/blog/">뉴스</a>
</nav>

<h1>{{ post.title }}</h1>
<h4>{{ post.created_at }}</h4>
<p>{{ post.content }}</p>
<hr/>

<h3>여기 댓글이 들어올 수 있겠죠?</h3>
</body>
</html>

qna/templates/qna/post_form.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}
<html>
<head>
<style>
    .container{ margin: 50px;}
</style>
</head>

<body>

{% include 'blog/navbar.html' %}

{% block main_area %}
<div class="container">
   <h1>Create New Post</h1>
</div>
   <hr/>

<div class="container">
   <form method="post" enctype="multipart/form-data">{% csrf_token %}
     <table>
         {{ form | crispy }}
         <div id="div_id_tags_str">
             <label for="id_tags_str">Tags:</label>
             <input type="text" name="tags_str" id="id_tags_str" class="textinput textInput form-control">
         </div>
         <br/>
     </table>
     <button type="submit" class="btn btn-primary float-right">Submit</button>
   </form>
{% endblock %}
    </div>


{% include 'blog/footer.html' %}
</body>
</html>

qna/templates/qna/post_list.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
<meta charset='utf-8'>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

<style>
    *{padding:0%; margin:0%;}

    li{list-style-type: none;}

    .all button{float: right; margin: 5px;}

    .button2{margin-left: 300px;}

    .search{}

    .dropdown{margin-left: 220px;}

    .list{margin-top: 40px;}

    .pa{margin-left: 680px; margin-top: 40px; margin-bottom: 40px;}


    .container{ margin: 30px;}



</style>
<title>COBI Q&A 전체페이지</title>
</head>

<body>
    {% include 'blog/navbar.html' %}

<div class="container">
   <div class="search">
      <!-- As a link -->
     <nav class="navbar navbar-light bg-light">
     <a class="navbar-brand" href="#">전체 Q&A</a>

        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" aria-colspan="500">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>

                <div class="dropdown">
                    {% if user.is_authenticated %}
                    {% if user.is_superuser or user.is_staff %}
                        <div class="button2">
                            <a href="/qna/create_post/" class="btn btn-primary">Q&A 하기</a>
                        </div>
                    {% endif %}
                    {% endif %}
                </div>

        </form>
     </nav>
    </div>
    </div>

    <div class="container mb-10">
        <ul>
            <li>
                <div class="list-group">
                    <a href="#" class="list-group-item list-group-item-action active" aria-current="true">
                    Q&A 카테고리
                    </a>
                    {% for category in categories %}
                    <a href="{{ category.get_absolute_url }}" class="list-group-item list-group-item-action">{{ category }}
                        ({{ category.post_set.count }})</a>
                    {% endfor %}
                    <a href="/qna/category/no_category/" class="list-group-item list-group-item-action">기타 의료 질문
                        ({{ no_category_post_count }})</a>
                </div>
            </li>
        </ul>
    </div>

    <hr>



    <div class="list">
        <div class="container">
            <h1>Q&A {% if category %}<span class="badge badge-secondary">{{ category }}</span>
    {% endif %}</h1>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">작성일</th>
                <th scope="col">제목</th>
                <th scope="col">내용</th>
                <th scope="col">작성자</th>
            </tr>
            </thead>

           {% for p in post_list %}
            <tbody>
            <tr>
                <th scope="row">{{ p.created_at }}</th>
                <td><a href="{{ p.get_absolute_url }}">{{ p.title | truncatechars:10 }}</a></td>
                <td id="post-{{ p.pk }}">{{ p.context | truncatechars:10 }}</td>
                {% if p.category %}
                <td><a href="#">{{ p.author | upper }}</a> <span class="badge badge-secondary float-right">{{ p.category }}</span> </td>
                {% else %}
                <td><a href="#">{{ p.author | upper }}</a> <span class="badge badge-secondary float-right">기타 의료 질문</span> </td>
                {% endif %}
            </tr>
            </tbody>
            {% endfor %}

        </table>
        </div>
    </div>


{% include 'blog/footer.html' %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
</body>
</html>

qna/templates/qna/post_update_form.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}
<html>
<head>
{% block head_title %}Edit Post - Q&A{% endblock %}
</head>

<body>
{% include 'blog/navbar.html' %}

{% block main_area %}
   <h1>Edit Post</h1>
   <hr/>
   <div class="container">
   <form method="post" enctype="multipart/form-data">{% csrf_token %}
     <table>
         {{ form | crispy }}
     </table>
     <button type="submit" class="btn btn-primary float-right">Submit</button>
   </form>
   </div>
{% endblock %}


{% include 'blog/footer.html' %}
</body>
</html>

single_pages/templates/single_pages/landing.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
<meta charset='utf-8'>
<style>
body{
		background-color:#002850;
		width: 1180px;
		margin: auto;
	}

span{ color: white;
    text-align : center;
    font-size: xx-large;
    }

.mainbox{
    display: flex;
    justify-content: space-evenly;
   /* flex-direction: column;
    align-items: center;*/
    padding-top: 100px;
}
.box1{
/*	margin-right: 900px;
    margin-left: 100px;
    margin-bottom: 30px;*/
    background-color: white;
    padding-bottom: 0px;
    border-radius: 10px;
    }
.box2{
/*	margin-right: 900px;
    margin-left: 100px;
    margin-bottom: 30px;*/
    background-color: white;
    padding-bottom: 0px;
    border-radius: 10px;

    }
.box3{
	/*margin-right: 900px;
    margin-left: 100px;
    margin-bottom: 30px;*/
    background-color: white;
    padding-bottom: 0px;
    border-radius: 10px;

    }
.list{
    text-align: center;

}
a{
    text-decoration: none;
    text-decoration-color: black;
    text-decoration-line: none;
  }

</style>
<title>COBI 메인화면</title>

<nav>
   <h1> <span> COBI </span> </h1>

<hr/>
</nav>

</head>

<body>


<div class="mainbox">

    <div class="box1">
        <img src="./images/community.png" height="200" width="205">

        <div class="list">
        <p><a href=walam-html/coming.html>병원 찾기</a></p>
        <hr/>
        <p><a href=walam-html/coming.html> 약국찾기</a></p>
        <hr/>

        <p><a href=walam-html/coming.html>의약품정보조회 </a></p>

        </div>
    </div>

    <div class="box2">
    <img src="./images/medic.png" height="200" width="210">
    <div class="list">
        <p><a href="/self/">자가진단</a></p>
        <hr/>
        <p><a href=walam-html/coming.html>비대면진료 </a></p>
        <hr/>
        <p><a href=walam-html/coming.html>내건강기록 </a></p>

        </div>
    </div>

    <div class="box3">
    <img src="./images/search.png" height="200" width="220">
    <div class="list">

        <p><a href="/blog/"> 의학 뉴스 </a></p>
        <hr/>
        <p><a href="/qqq/"> Q&A </a></p>


        <hr/>
        </div>
    </div>

</div>

</body>
</html>